import { serialize, Children } from '@/utils/serialize';

//generic type definition generated by PayloadCMS for rich text fields
type Content = {
  [k: string]: unknown;
}[];

type RichTextProps = {
  content?: Content;
};

export function RichText({ content }: RichTextProps) {
  const serializableContent = content as Children | undefined;

  if (!serializableContent) {
    return null;
  }

  return <>{serialize(serializableContent)}</>;
}
